// Docs: https://www.instantdb.com/docs/modeling-data

import { i } from "@instantdb/react";

const _schema = i.schema({
  entities: {
    $files: i.entity({
      path: i.string().unique().indexed(),
      url: i.string(),
    }),
    $streams: i.entity({
      abortReason: i.string().optional(),
      clientId: i.string().unique().indexed(),
      done: i.boolean().optional(),
      size: i.number().optional(),
    }),
    $users: i.entity({
      email: i.string().unique().indexed().optional(),
      imageURL: i.string().optional(),
      type: i.string().optional(),
    }),
    corpses: i.entity({
      createdAt: i.any().optional(),
      deathId: i.any().optional(),
      discovered: i.any().optional(),
      discoveredBy: i.any().optional(),
      finalMessage: i.any().optional(),
      isAgent: i.any().optional(),
      killedBy: i.any().optional(),
      loot: i.any().optional(),
      lootEmoji: i.any().optional(),
      playerName: i.any().optional(),
      room: i.any().optional(),
      tipAmount: i.any().optional(),
      tipped: i.any().optional(),
      walletAddress: i.any().optional(),
      zone: i.any().optional(),
    }),
    deaths: i.entity({
      agentName: i.any().optional(),
      createdAt: i.any().optional(),
      deathHash: i.any().optional(),
      finalMessage: i.any().optional(),
      inventory: i.any().optional(),
      isAgent: i.any().optional(),
      killedBy: i.any().optional(),
      likeCount: i.any().optional(),
      nowPlayingArtist: i.any().optional(),
      nowPlayingTitle: i.any().optional(),
      onChainSignature: i.any().optional(),
      playerName: i.any().optional(),
      room: i.any().optional(),
      stakeAmount: i.any().optional(),
      tapestryContentId: i.any().optional(),
      walletAddress: i.any().optional(),
      zone: i.any().optional(),
    }),
    gameSettings: i.entity({
      baseDamageMax: i.any().optional(),
      baseDamageMin: i.any().optional(),
      enabledZones: i.any().optional(),
      enableMagicBlock: i.any().optional(),
      enableRoomTextStreaming: i.any().optional(),
      enableVRF: i.any().optional(),
      lootChanceBase: i.any().optional(),
      lootChanceDepth5: i.any().optional(),
      lootChanceDepth9: i.any().optional(),
      roomTextStreamSpeedMs: i.any().optional(),
      showLeaderboardLink: i.any().optional(),
      showVictorsFeed: i.any().optional(),
      tier2Multiplier: i.any().optional(),
      tier3Multiplier: i.any().optional(),
      victoryBonusPercent: i.any().optional(),
    }),
    players: i.entity({
      authId: i.string().optional().indexed(),
      authType: i.any().optional(),
      clearedZones: i.any().optional(),
      createdAt: i.any().optional(),
      creatureMastery: i.any().optional(),
      highestRoom: i.any().optional(),
      lastPlayedAt: i.any().optional(),
      nickname: i.any().optional(),
      notifPrompted: i.any().optional(),
      totalClears: i.any().optional(),
      totalDeaths: i.any().optional(),
      totalEarned: i.any().optional(),
      totalLikesReceived: i.any().optional(),
      totalLost: i.any().optional(),
      totalRuns: i.any().optional(),
      totalTipsReceived: i.any().optional(),
      totalTipsSent: i.any().optional(),
      walletAddress: i.any().optional(),
      zonesCleared: i.any().optional(),
    }),
    playlists: i.entity({
      audiusId: i.any().optional(),
      emoji: i.any().optional(),
      enabled: i.any().optional(),
      name: i.any().optional(),
      order: i.any().optional(),
      trackCount: i.any().optional(),
      vibe: i.any().optional(),
    }),
    sessions: i.entity({
      agentName: i.any().optional(),
      authId: i.any().optional(),
      burnStacks: i.any().optional(),
      chillStacks: i.any().optional(),
      clarity: i.any().optional(),
      createdAt: i.any().optional(),
      currentRoom: i.any().optional(),
      demoMode: i.any().optional(),
      dungeon: i.any().optional(),
      enableVrf: i.any().optional(),
      endedAt: i.any().optional(),
      enemyFrozen: i.any().optional(),
      enemyHealth: i.any().optional(),
      enemyIntent: i.any().optional(),
      erCommitTx: i.any().optional(),
      erRunId: i.any().optional(),
      escrowSessionId: i.any().optional(),
      finalMessage: i.any().optional(),
      finalRoom: i.any().optional(),
      fluxActive: i.any().optional(),
      health: i.any().optional(),
      infectionDebuff: i.any().optional(),
      infectionStacks: i.any().optional(),
      inventory: i.any().optional(),
      isAgent: i.any().optional(),
      lastAdvancedAt: i.any().optional(),
      maxHealth: i.any().optional(),
      maxRooms: i.any().optional(),
      payoutStatus: i.any().optional(),
      payoutTx: i.any().optional(),
      playerName: i.any().optional(),
      reward: i.any().optional(),
      room: i.any().optional(),
      seed: i.any().optional(),
      seedSource: i.any().optional(),
      stakeAmount: i.any().optional(),
      stakeMode: i.any().optional(),
      stamina: i.any().optional(),
      startedAt: i.any().optional(),
      status: i.any().optional(),
      token: i.any().optional(),
      totalRooms: i.any().optional(),
      txSignature: i.any().optional(),
      useEscrow: i.any().optional(),
      visitedRooms: i.any().optional(),
      walletAddress: i.any().optional(),
      wasCharging: i.any().optional(),
      zone: i.any().optional(),
      zoneId: i.any().optional(),
    }),
  },
  links: {
    $streams$files: {
      forward: {
        on: "$streams",
        has: "many",
        label: "$files",
      },
      reverse: {
        on: "$files",
        has: "one",
        label: "$stream",
        onDelete: "cascade",
      },
    },
    $usersLinkedPrimaryUser: {
      forward: {
        on: "$users",
        has: "one",
        label: "linkedPrimaryUser",
        onDelete: "cascade",
      },
      reverse: {
        on: "$users",
        has: "many",
        label: "linkedGuestUsers",
      },
    },
  },
  rooms: {},
});

// This helps TypeScript display nicer intellisense
type _AppSchema = typeof _schema;
interface AppSchema extends _AppSchema {}
const schema: AppSchema = _schema;

export type { AppSchema };
export default schema;
